export const CONTRACT_ADDRESS = {
  OpenVoucher: process.env.NEXT_PUBLIC_OPEN_VOUCHER_CONTRACT_ADDRESS_KAIA!,
  KRWO: process.env.NEXT_PUBLIC_KRWO_CONTRACT_ADDRESS_KAIA!,
  GimSwap: process.env.NEXT_PUBLIC_GIM_SWAP_CONTRACT_ADDRESS_KAIA!,
};
