export const CONTRACT_ADDRESS = {
  OpenVoucher: process.env.NEXT_PUBLIC_OPEN_VOUCHER_CONTRACT_ADDRESS!,
  KRWO: process.env.NEXT_PUBLIC_KRWO_CONTRACT_ADDRESS!,
  GimSwap: process.env.NEXT_PUBLIC_GIM_SWAP_CONTRACT_ADDRESS!,
  SMART_LIQUIDITY_PROVIDER:
    process.env.NEXT_PUBLIC_SMART_LIQUIDITY_PROVIDER_CONTRACT_ADDRESS!,
};
