import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topbar from "../../components/navbar/Topbar";
import Footer from "../../components/navbar/Footer/Footer";
import { TopbarStoreProvider } from "@/src/lib/stores/topbarStore/TopbarStoreProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "GIM SWAP",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const pretendard = localFont({
  src: [
    {
      path: "../../../public/fonts/Pretendard-Regular.subset.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Pretendard-Medium.subset.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Pretendard-Bold.subset.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
});

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale} className={pretendard.variable}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <TopbarStoreProvider>
            <Topbar />
            {children}
            <Footer />
          </TopbarStoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
